flower: flower.hs
	ghc --make flower.hs -o bin/flower
	bin/flower -p -o flower.svg -w 600
	open flower.svg


vector: vector.hs
	ghc --make vector.hs -o bin/vector
	bin/vector -p -o vector.svg -w 600
	open vector.svg

points: points.hs
	ghc --make points.hs -o bin/points
	bin/points -p -o points.svg -w 600
	open points.svg

