vectors: vectors.hs
	ghc --make vectors.hs -o bin/vectors
	bin/vectors -p -o vectors.svg -w 600
	open vectors.svg

points: points.hs
	ghc --make points.hs -o bin/points
	bin/points -p -o points.svg -w 600
	open points.svg

exercise: exercise.hs
	ghc --make exercise.hs -o bin/exercise
	bin/exercise -p -o exercise.svg -w 600
	open exercise.svg
