vectors: vectors.hs
	ghc --make vectors.hs -o bin/vectors
	bin/vectors -p -o vectors.svg -w 600
	open vectors.svg

exercise: exercise.hs
	ghc --make exercise.hs -o bin/exercise
	bin/exercise -p -o exercise.svg -w 600
	open exercise.svg
